//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>

class MainDialogBaseClass : public wxDialog
{
protected:
    wxStaticText* m_staticTextID;
    wxTextCtrl* m_textCtrlID;
    wxStaticText* m_staticTextPW;
    wxTextCtrl* m_textCtrlPW;
    wxButton* m_buttonOK;

protected:
    virtual void OnExit(wxCloseEvent& event) { event.Skip(); }
    virtual void OnInit(wxInitDialogEvent& event) { event.Skip(); }
    virtual void OnButtonOK(wxCommandEvent& event) { event.Skip(); }

public:
    MainDialogBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("GunZ Login"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(300,150), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~MainDialogBaseClass();
};

#endif
