#ifndef __MMESSAGEID_H__
#define __MMESSAGEID_H__

#define MSG_OK	0

// cserror.xml .

#define MERR_WRONG_LOGINID			10000
#define MERR_ALREADY_CONNECTED		10001
#define MERR_WRONG_CMDVERSION		10002
#define MERR_SERVER_FULL			10003
#define MERR_BANNED_ID				10004
#define MERR_USERAUTH_FAIL			10005
#define MERR_MULTIPLE_LOGIN			10006
#define MERR_LOGIN_FAILED			10007
#define MERR_UNKNOWN_ACCOUNTINFO	10008
#define MERR_INVALID_CLIENT			10009
#define MERR_FAST_RECONNECT			10010
#define MERR_BLOCKED_REGION			10011
#define MERR_LOGININFO_EXPIRED		10012

#define MERR_CHARACTER_EXISTS		10100
#define MERR_INVALID_STRING			10101
#define MERR_NAME_SHORT				10102
#define MERR_NAME_LONG				10103
#define MERR_ENTER_NAME				10104
#define MERR_CHARACTER_NOT_EXISTS	10110
#define MERR_DELETE_CHARACTER_FAIL	10111

#define MERR_CANNOT_JOIN_CHANNEL						30020
#define MERR_CHANNEL_MAXPLAYERS_REACHED					30021
#define MERR_CANNOT_JOIN_CHANNEL_BY_LEVELLIMIT			30022
#define MERR_CANNOT_JOIN_CHANNEL_BY_HIGHLEVEL_CHARACTER	30023

#define MERR_LACKING_BOUNTY							20001
#define MERR_CANNOT_BUY_ITEM						20002
#define MERR_CANNOT_EQUIP_ITEM						20003
#define MERR_CANNOT_TAKEOFF_ITEM					20004
#define MERR_CANNOT_SELL_ITEM						20005
#define MERR_CANNOT_SELL_EQUIPPED_ITEM				20006
#define MERR_ITEM_NOT_EXIST							20007
#define MERR_TOO_MANY_ITEM							20008
#define MERR_SELECTED_ITEM_NOT_EXIST				20009
#define MERR_ITEM_WEIGHT_OVER						20010
#define MERR_CANNOT_EQUIP_ITEM_BY_LEVEL				20011
#define MERR_CANNOT_EQUIP_ITEM_ON_SAME_WEAPONSLOT	20012
#define MERR_CANNOT_TAKEOFF_ITEM_BY_WEIGHT			20013
#define MERR_CANNOT_SELL_CASH_ITEM_ON_SHOP			20014
#define MERR_ITEM_SEX_MISMATCH						20015
#define MERR_CANNOT_SEND_TO_BANK					20017
#define MERR_ONLY_CASH_ITEM_ALLOWED_TO_SEND_BANK	20018
#define MERR_ITEM_REMOVED_BY_LEVELDOWN				20019
#define MERR_CANNOT_MULTIPLE_EQUIP					20020
#define MERR_CANNOT_USE_ITEM_OUTSIDE_QUESTSERVER	20021

#define MERR_LACKING_MEDAL							20033
#define MERR_MEDALSHOP_REFRESH_SUCCESS				20034
#define MERR_MEDALSHOP_REFRESH_FAIL					20035
#define MERR_MEDALSHOP_DCRATE_APPLIED				20036
#define MERR_MEDALSHOP_DCRATE_APPLICATION_FAIL		20037

#define MERR_CANNOT_JOIN_TO_STAGE			30000
#define MERR_STAGE_MAX_PLAYER_OVER			30001
#define MERR_STAGE_WRONG_PASSWORD			30002
#define MERR_STAGE_LEVEL_OUT_OF_RANGE		30003
#define MERR_FORCED_ENTRY_NOT_ALLOWED		30004
#define MERR_STAGE_BANNED					30005
#define MERR_STAGE_NOT_EXISTS				30006
#define MERR_STAGE_ALREADY_EXISTS			30007
#define MERR_CANNOT_CREATE_STAGE			30008
#define MERR_JOINABLE_STAGE_NOT_AVAILABLE	30009

#define MERR_CANNOT_VOTE				200000
#define MERR_CANNOT_VOTE_ON_LADDER		200001
#define MERR_VOTING_ALREADY				200002
#define MERR_VOTE_FAILED				200003
#define MERR_TIMELIMIT_10SEC_REMAINING	200004
#define MERR_TIMELIMIT_30SEC_REMAINING	200005
#define MERR_TIMELIMIT_60SEC_REMAINING	200006
#define MERR_INCREASE_STAGE_MAX_PLAYER	200007
#define MERR_PLAYER_NOT_READY			200008

#define MERR_CANNOT_CREATE_CLAN					30030
#define MERR_CANNOT_CLOSE_CLAN					30031
#define MERR_CLAN_ALREADY_EXISTS				30032
#define MERR_LACKING_CLAN_SPONSORS				30033
#define MERR_CLAN_SPONSOR_ALREADY_IN_CLAN		30034
#define MERR_CLAN_SPONSOR_NOT_ON_LOBBY			30035
#define MERR_WRONG_CLAN_NAME					30036
#define MERR_NOT_CLAN_MASTER					30037
#define MERR_NOT_CLAN_MASTER_OR_ADMIN			30038
#define MERR_JOINER_ALREADY_IN_CLAN				30039
#define MERR_INVALID_JOIN_PROCESS				30040
#define MERR_ALREADY_IN_CLAN					30041
#define MERR_JOINER_NOT_ON_LOBBY				30042
#define MERR_NOT_JOINED_TO_CLAN					30043
#define MERR_CANNOT_LEAVE_CLAN					30044
#define MERR_CANNOT_ADD_CLAN_ANYMORE			30045
#define MERR_TARGET_USER_NOT_FOUND				30046
#define MERR_NOT_SAME_CLAN						30047
#define MERR_CANNOT_CHANGE_CLAN_MEMBER_GRADE	30048
#define MERR_THE_CLAN_NOT_FOUND					30049
#define MERR_LACKING_BOUNTY_FOR_ESTABLISH_CLAN	30050
#define MERR_LACKING_LEVEL_FOR_ESTABLISH_CLAN	30051
#define MERR_NOTICE_CLAN_CLOSED					30052
#define MERR_NEW_CLAN_MASTER_NOT_FOUND_ON_LOBBY	30053

#define MERR_CANNOT_RESERVE_LADDER_CHALLENGE	30070
#define MERR_WRONG_TEAM_MEMBER					30071
#define MERR_TEAM_MEMBER_NOT_EXISTS				30072
#define MERR_LADDER_MEMBER_NOT_READY			30073
#define MERR_NOT_LADDER_SERVICE_TIME			30074

#define MERR_WRONG_CLAN							30080
#define MERR_MEMBER_NOT_EXISTS					30081
#define MERR_CLANWAR_MEMBER_NOT_READY			30082

#define MERR_NOT_DUELTOURNAMENT_CHANNEL				140000
#define MERR_DUELTOURNAMENT_ALREADY_JOINED			140001
#define MERR_DUELTOURNAMENT_FAILED_JOIN				140002
#define MERR_DUELTOURNAMENT_JOIN_TIMELIMIT_REACHED	140003
#define MERR_COULD_NOT_CREATE_DUELTOURNAMENT		140004
#define MERR_DUELTOURNAMENT_NOT_FOUND				140005
#define MERR_DUELTOURNAMENT_WRONG_SETTING			140006
#define MERR_COULD_NOT_START_DUELTOURNAMENT			140007
#define MERR_COMMUNICATION_UNSTABLE					140008
#define MERR_DUELTOURNAMENT_SERVICE_TIME			140009

#define MERR_LACKING_CASH					20027
#define MERR_BUYER_NOT_LOGGED_IN			20028
#define MERR_NOT_EXISTING_GIFT_TARGET		20029
#define MERR_WRONG_CASH_INFO				20030
#define MERR_CASH_SYSTEM_UNAVAILABLE		20031
#define MERR_CANCELED_PAYMENT				20032

// result.
#define MRESULT_CLAN_JOINED	100000

// notify.xml .

#define MATCHNOTIFY_NETWORK_CREATE_FAILED	10
#define MATCHNOTIFY_NETWORK_PORTINUSE		11
#define MATCHNOTIFY_NETWORK_NAT_ESTABLISH	15
#define MATCHNOTIFY_GENERAL_USER_NOTFOUND	51
#define MATCHNOTIFY_CHARACTER_NOT_EXIST		70
#define MATCHNOTIFY_STAGE_ALREADY_EXIST		100
#define MATCHNOTIFY_STAGE_NOT_EXIST			101
#define MATCHNOTIFY_STAGE_TEAMFULL			110
#define MATCHNOTIFY_CHATROOM_CREATE_SUCCEED	150
#define MATCHNOTIFY_CHATROOM_CREATE_FAILED	151
#define MATCHNOTIFY_CHATROOM_ALREADY_EXIST	152
#define MATCHNOTIFY_CHATROOM_NOT_EXIST		153
#define MATCHNOTIFY_CHATROOM_NOT_USING		154
#define MATCHNOTIFY_CHATROOM_JOIN_FAILED	155
#define MATCHNOTIFY_CHATROOM_USER_FULL		156
#define MATCHNOTIFY_CHATROOM_NOT_JOIN		157
#define MATCHNOTIFY_GAME_SPEEDHACK			200
#define MATCHNOTIFY_GAME_MEMORYHACK			201
#define MATCHNOTIFY_FRIEND_ALREADY_EXIST	251
#define MATCHNOTIFY_FRIEND_NOT_EXIST		252
#define MATCHNOTIFY_FRIEND_TOO_MANY_ADDED	253
#define MATCHNOTIFY_FRIEND_ADD_SUCCEED		255
#define MATCHNOTIFY_FRIEND_REMOVE_SUCCEED	256
#define MATCHNOTIFY_USER_WHISPER_REJECTED	301
#define MATCHNOTIFY_USER_WHISPER_IGNORED	302
#define MATCHNOTIFY_USER_INVITE_REJECTED	311
#define MATCHNOTIFY_USER_INVITE_IGNORED		312

// MC_GAME_START_FAIL.
#if _GAME_VERSION >= 2013
	#define GAMESTART_ERROR_PLAYER_NOT_READY		0
	#define GAMESTART_ERROR_UNAVAILABLE_SCENARIO	1
	#define GAMESTART_ERROR_INVALID_TICKET_USER		2
	#define GAMESTART_ERROR_INVALID_MAP				3
#else
	#define GAMESTART_ERROR_PLAYER_NOT_READY		1
	#define GAMESTART_ERROR_UNAVAILABLE_SCENARIO	2
	#define GAMESTART_ERROR_INVALID_TICKET_USER		3
	#define GAMESTART_ERROR_INVALID_MAP				4
#endif

#endif